name: Coverage

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  HUSKY: 0

jobs:
  coverage:
    name: Generate Coverage Badge
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Sources
        uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable

      - name: Setup Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: "yarn"

      - name: Setup EMSDK
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: 3.1.54
          actions-cache-folder: "emsdk-cache"

      - name: Install dependencies
        env:
          YARN_ENABLE_HARDENED_MODE: false
        run: yarn install --immutable

      - name: Build WASM
        run: yarn grammar:wasm

      - name: Build Extension
        run: yarn build

      - name: Run tests with coverage
        run: yarn test:cov:all

      - name: Run e2e tests (Linux only)
        if: runner.os == 'Linux'
        run: xvfb-run -a yarn run test:e2e:cov

      - name: Update coverage badge
        if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
        uses: we-cli/coverage-badge-action@main
