name: Nightly Release

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

env:
  HUSKY: 0

jobs:
  nightly-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable

      - name: Setup Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: "yarn"

      - name: Install dependencies
        env:
          YARN_ENABLE_HARDENED_MODE: false
        run: yarn install --immutable

      - name: Build Extension
        run: yarn build

      - name: Package Extension
        run: yarn package

      - name: Create Language Server Archive
        run: |
          VERSION=$(node -p "require('./package.json').version")
          mkdir -p tact-language-server
          cp -r dist/* tact-language-server/
          cp package.json tact-language-server/
          tar -czf tact-language-server-v${VERSION}.tar.gz tact-language-server/
          zip -r tact-language-server-v${VERSION}.zip tact-language-server/

      - name: Update Nightly Release
        run: |
          VERSION=$(node -p "require('./package.json').version")

          gh release delete nightly --yes || true
          gh release create nightly \
            --title "Nightly Build v${VERSION}" \
            --notes "🌙 This is an automated nightly build from the master branch.

          ## VS Code Extension
          - Download the .vsix file and install it through VS Code

          ## Other Editors
          - Download tact-language-server-v${VERSION}.tar.gz (Linux/macOS) or tact-language-server-v${VERSION}.zip (Windows)
          - Extract it to a convenient location
          - Configure your editor to use the language server from the extracted folder" \
            --prerelease \
            --target master \
            *.vsix tact-language-server-v${VERSION}.tar.gz tact-language-server-v${VERSION}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
