name: Nightly Release

on:
  push:
    branches:
      - master

env:
  HUSKY: 0

jobs:
  nightly-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable

      - name: Setup Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: "yarn"

      - name: Install dependencies
        env:
          YARN_ENABLE_HARDENED_MODE: false
        run: yarn install --immutable

      - name: Build Extension
        run: yarn build

      - name: Package Extension
        run: yarn package

      - name: Update Nightly Release
        run: |
          VERSION=$(node -p "require('./package.json').version")

          gh release delete nightly --yes || true
          gh release create nightly \
            --title "Nightly Build v${VERSION}" \
            --notes "🌙 This is an automated nightly build from the master branch." \
            --prerelease \
            --target master \
            *.vsix
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
