on:
  pull_request:
    branches:
      - master
#    paths:
#      - tree-sitter-tact/**

defaults:
  run:
    working-directory: ./tree-sitter-tact

jobs:
  tree-sitter:
    name: Test (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-latest
          - ubuntu-latest
          - macos-latest
    steps:
      - name: Fetch Sources
        uses: actions/checkout@v4

      - name: Enable Corepack
        if: matrix.os == 'windows-latest'
        run: corepack enable --install-directory 'C:\npm\prefix'

      - name: Enable Corepack
        if: matrix.os != 'windows-latest'
        run: corepack enable

      - name: Setup Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: "yarn"

      - name: Setup EMSDK
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: 3.1.54
          actions-cache-folder: "emsdk-cache"

      - name: Install dependencies
        env:
          YARN_ENABLE_HARDENED_MODE: false
        run: yarn install --immutable

      - name: Run e2e tests
        run: yarn run test
