on:
  pull_request:
    branches:
      - master
#    paths:
#      - tree-sitter-tact/**

defaults:
  run:
    working-directory: ./tree-sitter-tact

jobs:
  tree-sitter:
    name: Test (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-latest
          - ubuntu-latest
          - macos-latest
    steps:
      - name: Fetch Sources
        uses: actions/checkout@v4

      - name: Set up tree-sitter
        uses: tree-sitter/setup-action/cli@v1
        with:
          tree-sitter-ref: v0.25.0

      - name: Run tests
        uses: tree-sitter/parser-test-action@v2
        with:
          generate: true
          test-parser: true
          test-node: true
